server:
  port: 8021
spring:
  application:
    name: user-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.10.11:3306/springcloud_db01?serverTimezone=GMT%2B8
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 150
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.109:6001/eureka,http://192.168.1.109:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.mengxuegu.bill.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis.cfg.xml